SELECT totalData
FROM (
         select count(1) as totalData
         from (
                  SELECT sum(table_1610091062766.column_f594a0240a) column_f594a0240a_sum
                       , sum(table_1610091062766.column_b4cea8f96f) column_b4cea8f96f_sum
                       , table_1610091062766.column_3ada5c824f      column_3ada5c824f_day
                  FROM (
                           SELECT `column_3ada5c824f`,
                                  `column_adc5a44950`,
                                  `column_93c183f762`,
                                  `column_820ef665af`,
                                  `column_6ca90fb412`,
                                  `column_49044c5dc6`,
                                  `column_e0f8d57464`,
                                  `column_957cc363d8`,
                                  `column_8cb54ac87e`,
                                  `column_ce231173d7`,
                                  `column_f0fbae15aa`,
                                  `column_fc26496a76`,
                                  `column_6788c2f326`,
                                  `column_af70da0d1e`,
                                  `column_49f7a3e656`,
                                  `column_fc7d7b3ee9`,
                                  `column_3431d37607`,
                                  `column_1b4eb1902a`,
                                  `column_c442efecdd`,
                                  `column_a7f112c867`,
                                  `column_b852aff8ce`,
                                  `column_ca95a794e9`,
                                  `column_4f2089af82`,
                                  `column_31724fa1d1`,
                                  `column_197ecc3ad9`,
                                  `column_447dca2695`,
                                  `column_969af90d75`,
                                  `column_809f3bd685`,
                                  `column_18af2dbdbd`,
                                  `column_48837d44ba`,
                                  `column_b3cef5f559`,
                                  `column_688f139753`,
                                  `column_b989b0dedf`,
                                  `column_0363716d2d`,
                                  `column_102e6f7565`,
                                  `column_f49b36d398`,
                                  `column_de1d606f37`,
                                  `column_8aa61471d9`,
                                  `column_0e0a6bb05a`,
                                  `column_8dbed5c979`,
                                  `column_02ce5ff534`,
                                  `column_de523e16dd`,
                                  `column_09e0208694`,
                                  `column_f7d1d7c4ca`,
                                  `column_8c546c101e`,
                                  `column_4917f9274b`,
                                  `column_993f8ac3a3`,
                                  `column_9f65ee57d5`,
                                  `column_32ba567887`,
                                  `column_c4156cd18e`,
                                  `column_9fe5cc2c5c`,
                                  `column_4d4b1d815f`,
                                  `column_3ed75e78a3`,
                                  `column_3c6f32c6ed`,
                                  `column_8828d1c3e7`,
                                  `column_32d5719338`,
                                  `column_36a985eee5`,
                                  `column_33ffe4b0cd`,
                                  `column_de8128a026`,
                                  `column_89391b8f0e`,
                                  `column_e95975eb3f`,
                                  `column_5abfa8e470`,
                                  `column_4cdefd9b87`,
                                  `column_e54f895e52`,
                                  `column_0558028ce1`,
                                  `column_049eb52866`,
                                  `column_a63f1f37e3`,
                                  `column_d6ff18a3a7`,
                                  `column_8c3d5fb93d`,
                                  `column_6f7bfee6d6`,
                                  `column_65961cf81a`,
                                  `column_1c11a4b159`,
                                  `column_94778fe63b`,
                                  `column_f443703fc3`,
                                  `column_40902ab92b`,
                                  `column_af3a06c138`,
                                  `column_1b39ebdbbc`,
                                  `column_6c3b21632e`,
                                  `column_f4d89d5fc6`,
                                  `column_d180f01fba`,
                                  `column_b53ba186a9`,
                                  `column_923c17422b`,
                                  `column_8005189d98`,
                                  `column_9f614b9014`,
                                  `column_13b61674ff`,
                                  `column_2fcd50a3c9`,
                                  `column_512ddde1ba`,
                                  `column_2f6aa67c17`,
                                  `column_a90539cb5f`,
                                  `column_dabc1cbb64`,
                                  `column_c51f2d26ba`,
                                  `column_55a0693fbe`,
                                  `column_b4a3a485fa`,
                                  `column_d64142e32c`,
                                  `column_4ff4867016`,
                                  `column_ecd2302962`,
                                  `column_e177c116a6`,
                                  `column_4d37de399e`,
                                  `column_ef5cd06b46`,
                                  `column_bea9627d81`,
                                  `column_8fe1e11072`,
                                  `column_f5b3012073`,
                                  `column_dc39ed6550`,
                                  `column_5521c3109b`,
                                  `column_8d611c61a0`,
                                  `column_e1289c2a73`,
                                  `column_1a76f51fbf`,
                                  `column_91ab0b3813`,
                                  `column_aeb91c33d7`,
                                  `column_35efd5915b`,
                                  `column_13bf9ac5ce`,
                                  `column_0ee4d6e3e8`,
                                  `column_f72f7e9017`,
                                  `column_3e74d2165e`,
                                  `column_e567d9d700`,
                                  `column_01baaa7ac7`,
                                  `column_fa27d40a96`,
                                  `column_7d9b102e1d`,
                                  `column_3bd77ba573`,
                                  `column_c8a38063b2`,
                                  `column_b93aa4a51c`,
                                  `column_8c507e764d`,
                                  `column_741498c17a`,
                                  `column_4d9151ee67`,
                                  `column_b334a57309`,
                                  `column_535e1449bf`,
                                  `column_7a8a794ca0`,
                                  `column_7ae2987108`,
                                  `column_6d17b0e8bf`,
                                  `column_b4cea8f96f`,
                                  `column_f594a0240a`,
                                  `column_d54c5c6b08`,
                                  `column_dcb0ead077`,
                                  `column_ef36d0b2c6`,
                                  `column_5f6e508bd2`,
                                  `column_d1a007d651`,
                                  `column_f99ecbfb36`,
                                  `column_e83cbd1924`,
                                  `column_fb948bebf4`,
                                  `column_7f9b258308`,
                                  `column_3cef219924`,
                                  `column_b395d3fca1`,
                                  `column_d2a603692d`,
                                  `column_5e6472be84`,
                                  `column_04f90b0162`,
                                  `column_34f821ea62`,
                                  `column_f081be20a5`,
                                  `column_ead81b4dfc`,
                                  `column_86fc5ecea5`,
                                  `column_22302c7ce9`,
                                  `column_f508383bcf`,
                                  `column_3405cc4c22`
                           FROM (
                                    SELECT `dt`                          AS column_3ada5c824f,
                                           `activity_id`                 AS column_adc5a44950,
                                           `actual_pay_time`             AS column_93c183f762,
                                           `addr`                        AS column_820ef665af,
                                           `addr_detail`                 AS column_6ca90fb412,
                                           `aft_type_name`               AS column_49044c5dc6,
                                           `after_sale_order_id`         AS column_e0f8d57464,
                                           `after_sale_type_id`          AS column_957cc363d8,
                                           `bd_name`                     AS column_8cb54ac87e,
                                           `bd_phone`                    AS column_ce231173d7,
                                           `bdm_name`                    AS column_f0fbae15aa,
                                           `bdm_phone`                   AS column_fc26496a76,
                                           `biz_id`                      AS column_6788c2f326,
                                           `biz_type_name`               AS column_af70da0d1e,
                                           `brand`                       AS column_49f7a3e656,
                                           `category_id`                 AS column_fc7d7b3ee9,
                                           `category_name`               AS column_3431d37607,
                                           `check_time`                  AS column_1b4eb1902a,
                                           `company_name`                AS column_c442efecdd,
                                           `confirm_receipt_time`        AS column_a7f112c867,
                                           `coordinate`                  AS column_b852aff8ce,
                                           `create_time`                 AS column_ca95a794e9,
                                           `custom_tag`                  AS column_4f2089af82,
                                           `custom_tag_name`             AS column_31724fa1d1,
                                           `develop_channel_name`        AS column_197ecc3ad9,
                                           `discount_details`            AS column_447dca2695,
                                           `expect_send_time`            AS column_969af90d75,
                                           `field1`                      AS column_809f3bd685,
                                           `goods_id`                    AS column_18af2dbdbd,
                                           `goods_name`                  AS column_48837d44ba,
                                           `goods_type_name`             AS column_b3cef5f559,
                                           `group_id`                    AS column_688f139753,
                                           `has_store_name`              AS column_b989b0dedf,
                                           `inviter_id`                  AS column_0363716d2d,
                                           `inviter_phone`               AS column_102e6f7565,
                                           `inviter_type`                AS column_f49b36d398,
                                           `inviter_type_name`           AS column_de1d606f37,
                                           `inviter_zh_name`             AS column_8aa61471d9,
                                           `is_first_order_user`         AS column_0e0a6bb05a,
                                           `latitude`                    AS column_8dbed5c979,
                                           `lead_city_id`                AS column_02ce5ff534,
                                           `lead_city_name`              AS column_de523e16dd,
                                           `lead_county_id`              AS column_09e0208694,
                                           `lead_county_name`            AS column_f7d1d7c4ca,
                                           `lead_pro_id`                 AS column_8c546c101e,
                                           `lead_pro_name`               AS column_4917f9274b,
                                           `leader_create_time`          AS column_993f8ac3a3,
                                           `leader_id`                   AS column_9f65ee57d5,
                                           `leader_name`                 AS column_32ba567887,
                                           `leader_phone`                AS column_c4156cd18e,
                                           `leader_self_uid`             AS column_9fe5cc2c5c,
                                           `leader_sex`                  AS column_4d4b1d815f,
                                           `leader_uid`                  AS column_3ed75e78a3,
                                           `leader_wx_open_id`           AS column_3c6f32c6ed,
                                           `level_1_id`                  AS column_8828d1c3e7,
                                           `level_1_name`                AS column_32d5719338,
                                           `level_2_id`                  AS column_36a985eee5,
                                           `level_2_name`                AS column_33ffe4b0cd,
                                           `level_3_id`                  AS column_de8128a026,
                                           `level_3_name`                AS column_89391b8f0e,
                                           `longitude`                   AS column_e95975eb3f,
                                           `odr_city_id`                 AS column_5abfa8e470,
                                           `odr_city_name`               AS column_4cdefd9b87,
                                           `order_id`                    AS column_e54f895e52,
                                           `order_label`                 AS column_0558028ce1,
                                           `order_type_name`             AS column_049eb52866,
                                           `origin`                      AS column_a63f1f37e3,
                                           `out_trade_id`                AS column_d6ff18a3a7,
                                           `overtime_close_time`         AS column_8c3d5fb93d,
                                           `pay_finish_time`             AS column_6f7bfee6d6,
                                           `phone`                       AS column_65961cf81a,
                                           `pic_url`                     AS column_1c11a4b159,
                                           `production_time`             AS column_94778fe63b,
                                           `reason_type_name`            AS column_f443703fc3,
                                           `recomment_phone`             AS column_40902ab92b,
                                           `recomment_zh_name`           AS column_af3a06c138,
                                           `refrigeration_type_name`     AS column_1b39ebdbbc,
                                           `remark`                      AS column_6c3b21632e,
                                           `sku_id`                      AS column_f4d89d5fc6,
                                           `source_name`                 AS column_d180f01fba,
                                           `specification`               AS column_b53ba186a9,
                                           `stat_time`                   AS column_923c17422b,
                                           `status_name`                 AS column_8005189d98,
                                           `stock_id`                    AS column_9f614b9014,
                                           `stock_name`                  AS column_13b61674ff,
                                           `store_type_name`             AS column_2fcd50a3c9,
                                           `storehouse_id`               AS column_512ddde1ba,
                                           `sub_order_id`                AS column_2f6aa67c17,
                                           `supplier_addr`               AS column_a90539cb5f,
                                           `supplier_code`               AS column_dabc1cbb64,
                                           `supplier_money`              AS column_c51f2d26ba,
                                           `supplier_province_id`        AS column_55a0693fbe,
                                           `supplier_type_name`          AS column_b4a3a485fa,
                                           `unit`                        AS column_d64142e32c,
                                           `update_time`                 AS column_4ff4867016,
                                           `user_id`                     AS column_ecd2302962,
                                           `user_phone`                  AS column_e177c116a6,
                                           `user_sex`                    AS column_4d37de399e,
                                           `warehouse_addr`              AS column_ef5cd06b46,
                                           `warehouse_code`              AS column_bea9627d81,
                                           `warehouse_name`              AS column_8fe1e11072,
                                           `wx_open_id`                  AS column_f5b3012073,
                                           `actual_deduct_commision_amt` AS column_dc39ed6550,
                                           `actual_goods_cnt`            AS column_5521c3109b,
                                           `after_sale_amt`              AS column_8d611c61a0,
                                           `after_sale_is_td_aft_apply`  AS column_e1289c2a73,
                                           `after_sale_is_td_aft_pass`   AS column_1a76f51fbf,
                                           `b_subsidy_amount`            AS column_91ab0b3813,
                                           `biz_type`                    AS column_aeb91c33d7,
                                           `can_invite`                  AS column_35efd5915b,
                                           `commission_amt`              AS column_13bf9ac5ce,
                                           `cost_price_amt`              AS column_0ee4d6e3e8,
                                           `develop_channel`             AS column_f72f7e9017,
                                           `evaluated`                   AS column_3e74d2165e,
                                           `field2`                      AS column_e567d9d700,
                                           `final_payment_amt`           AS column_01baaa7ac7,
                                           `goods_cnt`                   AS column_fa27d40a96,
                                           `goods_type`                  AS column_7d9b102e1d,
                                           `is_fresh`                    AS column_3bd77ba573,
                                           `is_fruits`                   AS column_c8a38063b2,
                                           `is_new_leader`               AS column_b93aa4a51c,
                                           `is_recruits`                 AS column_8c507e764d,
                                           `is_td_cancel`                AS column_741498c17a,
                                           `is_td_overtime`              AS column_4d9151ee67,
                                           `is_td_pay`                   AS column_b334a57309,
                                           `is_td_user_receive`          AS column_535e1449bf,
                                           `is_td_valid_pay`             AS column_7a8a794ca0,
                                           `is_vgtble`                   AS column_7ae2987108,
                                           `leader_age`                  AS column_6d17b0e8bf,
                                           `leader_ratio`                AS column_b4cea8f96f,
                                           `line_price`                  AS column_f594a0240a,
                                           `minimum_commission_amt`      AS column_d54c5c6b08,
                                           `number_perbox`               AS column_dcb0ead077,
                                           `order_type`                  AS column_ef36d0b2c6,
                                           `pay_amount_amt`              AS column_5f6e508bd2,
                                           `pre_sale_amt`                AS column_d1a007d651,
                                           `price`                       AS column_f99ecbfb36,
                                           `price_amt`                   AS column_e83cbd1924,
                                           `reason_type`                 AS column_fb948bebf4,
                                           `refrigeration_type`          AS column_7f9b258308,
                                           `sale_cnt`                    AS column_3cef219924,
                                           `source`                      AS column_b395d3fca1,
                                           `status`                      AS column_d2a603692d,
                                           `store_type`                  AS column_5e6472be84,
                                           `supplier_type`               AS column_04f90b0162,
                                           `total_price_amt`             AS column_34f821ea62,
                                           `user_active_coupons_amt`     AS column_f081be20a5,
                                           `user_after_coupons_amt`      AS column_ead81b4dfc,
                                           `user_coupons_amt`            AS column_86fc5ecea5,
                                           `user_discount_amt`           AS column_22302c7ce9,
                                           `user_subsidy_amt`            AS column_f508383bcf,
                                           `warehouse_type`              AS column_3405cc4c22
                                    FROM test_db.test_table
                                    WHERE (dt >= '2021-01-01 14:34')
                                ) tmp_0
                       ) table_1610091062766
                  WHERE (((((table_1610091062766.column_3ada5c824f BETWEEN '2021-01-02' AND '2021-01-31') AND
                            (table_1610091062766.column_93c183f762 BETWEEN '2021-01-02 00:00:00' AND '2021-01-31 23:59:59')) AND
                           (table_1610091062766.column_de523e16dd IN ('北京市', '石家庄市', '天津市', '广州市', '长沙市')))
                      AND (table_1610091062766.column_32ba567887 IN
                           ('邱萤', '沈淼', '严颖', '申驰', '张万旭', '张万英', '张世延', '张世演', '张世许',
                            '张东兴', '张业亮', '张东洋', '张中福', '张中萍', '张中馨', '张丽巧', '张丹阳',
                            '张亚方', '张仁谊', '张从沙', '张京卫', '张亚普', '张仕凤', '张传勇', '张伯均',
                            '张伴洁', '张佳蕾', '张俊定', '张俊杰', '张俊祥', '张保兴', '张信海', '张元开',
                            '张兆勋', '张兆花', '张先涛', '张凤兵', '张凯煌', '张刘道', '张华宾', '张友燕',
                            '张向华', '张后芹', '张召涛', '张变怀', '张如峰', '张如贵', '张威鹤', '张子轩',
                            '张孝蓉', '张宪芬', '张家奎', '张家根', '张家芸', '张常征', '张广灵', '张庆东',
                            '王泳', '王禹', '王圣', '王淀', '王谏', '王荷珍', '王晓翔', '王康彩', '王彦森',
                            '王子章', '王亚忠', '王红岐', '王守国', '王巳赟', '王聚晶', '王旋伟', '王佩光',
                            '王兴革', '王兴娣', '王喜雅', '王跃辉', '王怀健', '王锦鹤', '王春莺', '王贵芹',
                            '王大会', '王小马', '王玉坚', '王功合'))) AND
                         (table_1610091062766.column_4d4b1d815f IN ('男', '女')))
                  GROUP BY table_1610091062766.column_3ada5c824f
                  ORDER BY table_1610091062766.column_3ada5c824f DESC
              ) dps_data_center_cnt_sql_20210115
     ) tmp